<?php

declare(strict_types=1);

namespace KaririCode\Dotenv\Cache;

/**
 * Generates and reads OPcache-friendly PHP array cache files.
 *
 * In production, avoids .env parsing overhead by compiling all variables
 * into a `var_export()` PHP array. OPcache compiles this once — subsequent
 * requests load from shared memory with zero parsing cost.
 *
 * Inspired by Symfony's dotenv:dump but standalone (no framework required).
 *
 * @package KaririCode\Dotenv
 * @since   4.2.0
 */
final class PhpFileCache
{
    /**
     * Writes variables to a PHP cache file that returns an array when included.
     *
     * @param string                $path      Absolute path to the cache file.
     * @param array<string, string> $variables Variable name → raw string value.
     * @param string                $sourceHash MD5 of the source .env file(s) for invalidation.
     */
    public function dump(string $path, array $variables, string $sourceHash = ''): void
    {
        $metadata = [
            '__metadata' => [
                'generated_at' => date('c'),
                'source_hash' => $sourceHash,
                'generator' => 'KaririCode\\Dotenv v4.x',
            ],
        ];

        $export = var_export(array_merge($metadata, $variables), true);

        $content = <<<PHP
            <?php

            // Auto-generated by KaririCode\Dotenv — do not edit manually.
            // Regenerate with: php vendor/bin/kariricode-dotenv cache:dump

            return {$export};

            PHP;

        $tmpFile = $path . '.tmp.' . getmypid();

        if (file_put_contents($tmpFile, $content) === false) {
            throw new \RuntimeException("Failed to write cache file: {$path}");
        }

        // Atomic rename — prevents race conditions during deploy
        rename($tmpFile, $path);

        // Invalidate OPcache for this file so the new version is picked up
        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($path, true);
        }
    }

    /**
     * Reads a previously dumped cache file.
     *
     * @return array<string, string>|null Variables, or null if cache is missing/stale.
     */
    public function load(string $path, string $expectedHash = ''): ?array
    {
        if (!is_file($path) || !is_readable($path)) {
            return null;
        }

        $data = include $path;

        if (!is_array($data)) {
            return null;
        }

        // Validate source hash for staleness detection
        if ($expectedHash !== '') {
            $storedHash = $data['__metadata']['source_hash'] ?? '';
            if ($storedHash !== $expectedHash) {
                return null;
            }
        }

        // Strip metadata before returning
        unset($data['__metadata']);

        return $data;
    }

    public function clear(string $path): void
    {
        if (is_file($path)) {
            unlink($path);

            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($path, true);
            }
        }
    }

    /**
     * Computes a hash of the given file paths' contents for cache invalidation.
     *
     * @param list<string> $filePaths
     */
    public function computeSourceHash(array $filePaths): string
    {
        $context = hash_init('md5');

        foreach ($filePaths as $filePath) {
            if (is_file($filePath)) {
                hash_update($context, (string) filemtime($filePath));
                hash_update($context, (string) filesize($filePath));
            }
        }

        return hash_final($context);
    }
}
